name: CI with Maven, Coveralls and SonarCloud in Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      workdir: museum
    
    steps:
    - uses: actions/checkout@v3
      with:
        # Shallow clones should be disabled for a better relevancy of SonarQube analysis
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner. os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: >
        mvn verify -Pcoveralls sonar:sonar
        -DrepoToken=$COVERALLS_TOKEN -DpullRequest=${{ github.event.pull_request.number }}
        -Dsonar.organization=cosimogiani-github -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.projectKey=cosimogiani_museum
      working-directory: ${{ env.workdir }}
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Generate JUnit Report
      run: mvn surefire-report:report-only site:site -DgenerateReports=false
      working-directory: ${{ env.workdir }}
      if: ${{ always() }}
    - name: Archive Generated Reports
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: reports
        path: '**/target/site'